/// <reference types="@cloudflare/vitest-pool-workers" />

declare module "cloudflare:test" {
	// ProvidedEnv extends the Env type generated by `wrangler types`
	// Add test-specific bindings here if needed
	interface ProvidedEnv extends Env {}
}
